### PR TITLE
Remove Redux-related documetation

### PR DESCRIPTION
**Pull request by Aldomf**
This pull request addresses Issue #23 : Remove React-Redux Topics from Documentation Repository.

Removed all references and sections related to React-Redux from the documentation.
Files updated:
- README.md
- react-basics/README.md

### CODE REVIEW

**Review by AdityaSrivastava185 — CHANGES_REQUESTED** [review]
We need to completely remove the react-redux topic remove the file and all .

**Comment by Aldomf** [comment]
But there is no specific file for react-redux, which file would you like me to remove?

**Comment by AdityaSrivastava185** [comment]
Thank you very for your contrubution  and congratulations on your `Merged Changes` 🎉🎉
Every contribution counts 
Thank you

**Comment by Aldomf** [comment]
You're welcome! I'm really glad to contribute and happy that the changes were helpful. Thank you for the kind words, and I'm excited to keep contributing to the project! 🎉

**Pull request merged**
